apiVersion: v1
kind: Pod
metadata:
  name: etcd-backup
spec:
  containers:
    - name: etcd-backup
      image: bitnami/etcd:latest
      command:
        - /bin/sh
        - -c
        - |
          etcdctl snapshot save /backup/etcd_backup_$(date +%F).db
      volumeMounts:
        - name: nfs-storage
          mountPath: /backup

  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
